### ISSUE TITLE
_core.QgsProcessingException: Error: Algorithm qgis:extractspecificvertices not found 

### ISSUE THREAD

**Issue by rahulbhat44** [its4land/delineation-tool#3]
While processing I am getting an error. Is there any solution or is it a bug. I am using Qgis3.10 and I checked on qgis3.8 as well but the same error is coming.

**Comment by SCrommelinck** [comment]
Hi Rahul, I assume you already read my answer to your question under the[ manual video](https://www.youtube.com/watch?v=GrDv8fW53Fs) on YouTube. However, in case someone else runs into the same problem, here my answer:

I assume you did not enable the "Processing" plugin, which is installed in all QGIS versions by default. Could you try to enable it and retest?

**Comment by rahulbhat44** [comment]
Hi SCrommelinck,

Thanks, it worked after installing Processing Plugin. Thank you.
